---
disable_existing_loggers: false
filters: {}
formatters:
  console_verbose:
    datefmt: '%H:%M:%S'
    format: '[%(asctime)s,%(msecs)03d %(process)05d %(levelname)-0.1s] %(name)s %(funcName)s:%(lineno)d - %(message)s'
  file_verbose:
    format: '[%(asctime)s %(process)05d %(levelname)-0.1s] %(name)s %(funcName)s:%(lineno)d - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: console_verbose
    level: WARNING
    stream: ext://sys.stderr
  file:
    class: ansible_galaxy_cli.logger.setup.ExpandTildeWatchedFileHandler
    filename: '~/.ansible/galaxy-cli.log'
    formatter: file_verbose
    level: DEBUG
loggers:
  ansible_galaxy:
    handlers:
      - console
      - file
    level: DEBUG
  ansible_galaxy.archive.extract:
    level: INFO
  ansible_galaxy.flat_rest_api:
    level: DEBUG
  ansible_galaxy.flat_rest_api.content:
    level: DEBUG
  ansible_galaxy_cli:
    handlers:
      - console
      - file
    level: DEBUG
version: 1
