defaults: {}
servers:
  - ignore_certs: false
    token: null
    url: https://galaxy-qa.ansible.com
    # url: http://localhost:8000
content_roots:
  - ~/.ansible/content
  - /usr/share/ansible/content
options:
  local_tmp: ~/.ansible/tmp
  role_skeleton_ignore:
    - ^.git$
    - ^.*/.git_keep$
  role_skeleton_path: null
  verbosity: 0
version: 1
